server:
  port: 8080

spring:
 cloud:
    gateway:
      routes:
      - id: demo
        uri: http://localhost:8082
        predicates:
        - Path=/demo/**
        filters:
        - CacheRequestBody
        - RequestAudit
